version: '3'

services:
  db:
    image: ${MYSQL_IMAGE}
    restart: always
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST_NAME=${MYSQL_HOST_NAME}
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: ${ADMINER_CONTAINER_NAME}
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - app-network

volumes:
  data:
    driver: local

networks:
  app-network:
    driver: bridge
