"""add deadline

Revision ID: 76183748fad8
Revises: 6eed36cfb9c3
Create Date: 2023-11-02 21:30:39.318076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76183748fad8'
down_revision = '6eed36cfb9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
